# Development Dockerfile
FROM node:18-alpine

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Install NestJS CLI globally for development
RUN npm install -g @nestjs/cli

# Copy source code
COPY . .

# Expose the app's port
EXPOSE 3000

# Use hot-reloading
CMD ["npm", "run", "start:dev"]
