
services:
  # API Gateway (NestJS)
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://user:pass@postgres:5432/beer_db
      - HOP_SERVICE_URL=http://hop-service:4000
    depends_on:
      - hop-service
      - postgres
    volumes:
      - ./api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "start:dev"]

  # Hop Data Service (NestJS)
  hop-service:
    build:
      context: ./hop-service
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://user:pass@postgres:5432/beer_db
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./hop-service:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "start:dev"]

  # PostgreSQL Database
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: beer_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d beer_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
