# Docker Compose for Multi-Language Microservices
version: '3.8'

services:
  # Hop Data Service (NestJS)
  hop-service:
    build: ./hop-service
    ports:
      - "${PORT}:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./hop-service:/usr/src/app
    command: ["sh", "-c", "sleep 10 && npm run start:prod"]

  # PostgreSQL Database
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: beer_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d beer_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
